Further script improvements

diff --git a/autoKBL b/autoKBL
--- a/autoKBL
+++ b/autoKBL
@@ -10,41 +10,53 @@ HEADER="[${BLUE_COLOUR}AUTO KBL${WHITE_COLOUR}]"
 # Set name of keyboard
 #KEYBOARD_NAME="Logitech G513 RGB MECHANICAL GAMING KEYBOARD
 
-mapfile -t listFile < ~/.config/autoKBL.list
+
+if [ ! -f ~/.temp/autoKBL ]; then
+    touch ~/.temp/autoKBL
+fi
+
+if [ ! -f ~/.config/autoKBL.list ];then
+    echo -e "$HEADER Config file '~/.config/autoKBL.list' is missing, exiting autoKBL..."
+    exit 1
+else
+    if [ $(wc -l ~/.config/autoKBL.list | cut -d ' ' -f 1 ) -eq "0" ]; then
+	echo -e "$HEADER Config file empty, exiting autoKBL..."
+	exit 1
+    else
+	mapfile -t listFile < ~/.config/autoKBL.list
+    fi
+fi
+
+DEVICE_COUNT=0
 
 for line in "${listFile[@]}"; do
+
     LAYOUT=$(echo ${line} | cut -d '|' -f 1)
     KEYBOARD_NAME=$(echo ${line} | cut -d '|' -f 2)
+
     # Find the device ID of the keyboard
-    DEVICE_ID=$(xinput list --id-only "keyboard:""$KEYBOARD_NAME" 2>~/.temp/autoKBL.log)
+    DEVICE_ID=$(xinput list --id-only "keyboard:""$KEYBOARD_NAME" 2>>~/.temp/autoKBL)
+
     # Check if a device ID was found
-    if [ -z "$DEVICE_ID" ]; then
-      	echo -e "$HEADER Keyboard $KEYBOARD_NAME not detected."
-    else
-        echo -e "$HEADER Keyboard $KEYBOARD_NAME detected with device ID $DEVICE_ID."
+    if [ ! -z "$DEVICE_ID" ]; then
+        echo -e "$HEADER Keyboard $KEYBOARD_NAME detected with device ID $DEVICE_ID." >>~/.temp/autoKBL
+	
+	# Increment 
+	((DEVICE_COUNT++))
+        # Set the keyboard layout
+        setxkbmap -device "$DEVICE_ID" -layout "$LAYOUT"
 
-        # Find current layout
-        #CURR_LAYOUT=$(setxkbmap -device $DEVICE_ID -query | grep layout | awk '{print $2}')
-
-        #if [ -z "$CURR_LAYOUT" ]; then
-	#    exit 1
-        #else
-        #If not gb then update to gb
-        #    if [[ "$CURR_LAYOUT" != "$LAYOUT" ]]; then
-       	#       echo -e "$HEADER Device layout is '$CURR_LAYOUT', switching to '$LAYOUT'."
-                # Set the keyboard layout to GB
-	        setxkbmap -device "$DEVICE_ID" -layout "$LAYOUT"
-
-	        if [ $? -eq 0 ]; then
-	            echo -e "$HEADER $KEYBOARD_NAME ($DEVICE_ID) layout set to $LAYOUT."
-	        else
-    	            echo -e "$HEADER Failed to modify keyboard layout."
-    	            exit 1
-	        fi
-        #    else
-       	#        echo -e "$HEADER Device layout is '$LAYOUT', switch not required."
-        #    fi
-        #fi
+        if [ $? -eq 0 ]; then
+            echo -e "$HEADER $KEYBOARD_NAME ($DEVICE_ID) layout set to $LAYOUT."
+        else
+            echo -e "$HEADER Failed to modify keyboard layout for $KEYBOARD_NAME."
+            exit 1
+        fi
     fi
 done
-touch ~/.temp/autoKBL
+
+if [ "$DEVICE_COUNT" -eq "0" ];then
+    echo -e "$HEADER No configured devices detected."
+else
+    echo -e "$HEADER $DEVICE_COUNT device(s) setup."
+fi
